name: api_and_json_server
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  json_annotation: ^3.0.1
  cupertino_icons: ^1.0.0
  moor_flutter: ^3.1.0
  sqlite3_flutter_libs: ^0.3.0
  get_it: ^5.0.6
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  flutter_slidable: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.11.0
  moor_generator: ^3.4.1

flutter:
  uses-material-design: true 