name: api_and_json_server
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0-prev1
  json_annotation: ^4.0.0
  cupertino_icons: ^1.0.2
  moor_flutter: ^4.0.0-nullsafety
  sqlite3_flutter_libs: ^0.4.0+1
  get_it: ^6.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_slidable: ^0.6.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json_serializable: ^4.0.3
  json_serializable: ^4.0.2
  # build_runner: ^1.12.2
  build_runner: ^1.11.5
  moor_generator: ^4.1.0

flutter:
  uses-material-design: true 